// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderKV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderKV) Reset() {
	*x = HeaderKV{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderKV) ProtoMessage() {}

func (x *HeaderKV) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderKV.ProtoReflect.Descriptor instead.
func (*HeaderKV) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderKV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeaderKV) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OrderSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeNo       string                 `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	OutTradeNo    string                 `protobuf:"bytes,2,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	ApiTradeNo    string                 `protobuf:"bytes,3,opt,name=api_trade_no,json=apiTradeNo,proto3" json:"api_trade_no,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Plugin        string                 `protobuf:"bytes,6,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Channel       int64                  `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"`
	Cid           int64                  `protobuf:"varint,8,opt,name=cid,proto3" json:"cid,omitempty"`
	Code          int64                  `protobuf:"varint,9,opt,name=code,proto3" json:"code,omitempty"`
	Subject       string                 `protobuf:"bytes,10,opt,name=subject,proto3" json:"subject,omitempty"`
	Amount        int64                  `protobuf:"varint,11,opt,name=amount,proto3" json:"amount,omitempty"`
	Real          int64                  `protobuf:"varint,12,opt,name=real,proto3" json:"real,omitempty"`
	Fee           int64                  `protobuf:"varint,13,opt,name=fee,proto3" json:"fee,omitempty"`
	Get           int64                  `protobuf:"varint,14,opt,name=get,proto3" json:"get,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,15,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,16,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	Param         string                 `protobuf:"bytes,17,opt,name=param,proto3" json:"param,omitempty"`
	Domain        string                 `protobuf:"bytes,18,opt,name=domain,proto3" json:"domain,omitempty"`
	IpBuyer       string                 `protobuf:"bytes,19,opt,name=ip_buyer,json=ipBuyer,proto3" json:"ip_buyer,omitempty"`
	IpSource      string                 `protobuf:"bytes,20,opt,name=ip_source,json=ipSource,proto3" json:"ip_source,omitempty"`
	Buyer         string                 `protobuf:"bytes,21,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Status        int32                  `protobuf:"varint,22,opt,name=status,proto3" json:"status,omitempty"`
	Notify        int32                  `protobuf:"varint,23,opt,name=notify,proto3" json:"notify,omitempty"`
	ReqMs         int32                  `protobuf:"varint,24,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ReqCount      int32                  `protobuf:"varint,25,opt,name=req_count,json=reqCount,proto3" json:"req_count,omitempty"`
	ReqBody       string                 `protobuf:"bytes,26,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,27,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	Ext           string                 `protobuf:"bytes,28,opt,name=ext,proto3" json:"ext,omitempty"`
	Result        string                 `protobuf:"bytes,29,opt,name=result,proto3" json:"result,omitempty"`
	Endtime       *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=endtime,proto3" json:"endtime,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,32,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSnapshot) Reset() {
	*x = OrderSnapshot{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSnapshot) ProtoMessage() {}

func (x *OrderSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSnapshot.ProtoReflect.Descriptor instead.
func (*OrderSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *OrderSnapshot) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *OrderSnapshot) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *OrderSnapshot) GetApiTradeNo() string {
	if x != nil {
		return x.ApiTradeNo
	}
	return ""
}

func (x *OrderSnapshot) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *OrderSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderSnapshot) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *OrderSnapshot) GetChannel() int64 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *OrderSnapshot) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *OrderSnapshot) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderSnapshot) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OrderSnapshot) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderSnapshot) GetReal() int64 {
	if x != nil {
		return x.Real
	}
	return 0
}

func (x *OrderSnapshot) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *OrderSnapshot) GetGet() int64 {
	if x != nil {
		return x.Get
	}
	return 0
}

func (x *OrderSnapshot) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *OrderSnapshot) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *OrderSnapshot) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *OrderSnapshot) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *OrderSnapshot) GetIpBuyer() string {
	if x != nil {
		return x.IpBuyer
	}
	return ""
}

func (x *OrderSnapshot) GetIpSource() string {
	if x != nil {
		return x.IpSource
	}
	return ""
}

func (x *OrderSnapshot) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *OrderSnapshot) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderSnapshot) GetNotify() int32 {
	if x != nil {
		return x.Notify
	}
	return 0
}

func (x *OrderSnapshot) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *OrderSnapshot) GetReqCount() int32 {
	if x != nil {
		return x.ReqCount
	}
	return 0
}

func (x *OrderSnapshot) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *OrderSnapshot) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *OrderSnapshot) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *OrderSnapshot) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *OrderSnapshot) GetEndtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Endtime
	}
	return nil
}

func (x *OrderSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RefundSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundNo      string                 `protobuf:"bytes,1,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	TradeNo       string                 `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	OutRefundNo   string                 `protobuf:"bytes,3,opt,name=out_refund_no,json=outRefundNo,proto3" json:"out_refund_no,omitempty"`
	ApiRefundNo   string                 `protobuf:"bytes,4,opt,name=api_refund_no,json=apiRefundNo,proto3" json:"api_refund_no,omitempty"`
	Uid           int64                  `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Channel       int64                  `protobuf:"varint,6,opt,name=channel,proto3" json:"channel,omitempty"`
	Cid           int64                  `protobuf:"varint,7,opt,name=cid,proto3" json:"cid,omitempty"`
	Amount        int64                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,9,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReqMs         int32                  `protobuf:"varint,10,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ReqBody       string                 `protobuf:"bytes,11,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,12,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	Notify        int32                  `protobuf:"varint,13,opt,name=notify,proto3" json:"notify,omitempty"`
	Status        int32                  `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,15,opt,name=remark,proto3" json:"remark,omitempty"`
	Result        string                 `protobuf:"bytes,16,opt,name=result,proto3" json:"result,omitempty"`
	Endtime       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=endtime,proto3" json:"endtime,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundSnapshot) Reset() {
	*x = RefundSnapshot{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundSnapshot) ProtoMessage() {}

func (x *RefundSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundSnapshot.ProtoReflect.Descriptor instead.
func (*RefundSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *RefundSnapshot) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *RefundSnapshot) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RefundSnapshot) GetOutRefundNo() string {
	if x != nil {
		return x.OutRefundNo
	}
	return ""
}

func (x *RefundSnapshot) GetApiRefundNo() string {
	if x != nil {
		return x.ApiRefundNo
	}
	return ""
}

func (x *RefundSnapshot) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RefundSnapshot) GetChannel() int64 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *RefundSnapshot) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *RefundSnapshot) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundSnapshot) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *RefundSnapshot) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *RefundSnapshot) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *RefundSnapshot) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *RefundSnapshot) GetNotify() int32 {
	if x != nil {
		return x.Notify
	}
	return 0
}

func (x *RefundSnapshot) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RefundSnapshot) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RefundSnapshot) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RefundSnapshot) GetEndtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Endtime
	}
	return nil
}

func (x *RefundSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RefundSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TransferSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeNo       string                 `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	ApiTradeNo    string                 `protobuf:"bytes,2,opt,name=api_trade_no,json=apiTradeNo,proto3" json:"api_trade_no,omitempty"`
	OutTradeNo    string                 `protobuf:"bytes,3,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Business      int32                  `protobuf:"varint,5,opt,name=business,proto3" json:"business,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Channel       int64                  `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"`
	Cid           int64                  `protobuf:"varint,8,opt,name=cid,proto3" json:"cid,omitempty"`
	Code          int64                  `protobuf:"varint,9,opt,name=code,proto3" json:"code,omitempty"`
	Amount        int64                  `protobuf:"varint,10,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           int64                  `protobuf:"varint,11,opt,name=fee,proto3" json:"fee,omitempty"`
	Cost          int64                  `protobuf:"varint,12,opt,name=cost,proto3" json:"cost,omitempty"`
	BankName      string                 `protobuf:"bytes,13,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	CardName      string                 `protobuf:"bytes,14,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	CardNo        string                 `protobuf:"bytes,15,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	BranchName    string                 `protobuf:"bytes,16,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,17,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReqMs         int32                  `protobuf:"varint,18,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ReqBody       string                 `protobuf:"bytes,19,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,20,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	Notify        int32                  `protobuf:"varint,21,opt,name=notify,proto3" json:"notify,omitempty"`
	Status        int32                  `protobuf:"varint,22,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,23,opt,name=remark,proto3" json:"remark,omitempty"`
	Result        string                 `protobuf:"bytes,24,opt,name=result,proto3" json:"result,omitempty"`
	Endtime       *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=endtime,proto3" json:"endtime,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferSnapshot) Reset() {
	*x = TransferSnapshot{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferSnapshot) ProtoMessage() {}

func (x *TransferSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferSnapshot.ProtoReflect.Descriptor instead.
func (*TransferSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *TransferSnapshot) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *TransferSnapshot) GetApiTradeNo() string {
	if x != nil {
		return x.ApiTradeNo
	}
	return ""
}

func (x *TransferSnapshot) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *TransferSnapshot) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TransferSnapshot) GetBusiness() int32 {
	if x != nil {
		return x.Business
	}
	return 0
}

func (x *TransferSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransferSnapshot) GetChannel() int64 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TransferSnapshot) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *TransferSnapshot) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TransferSnapshot) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferSnapshot) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransferSnapshot) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *TransferSnapshot) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *TransferSnapshot) GetCardName() string {
	if x != nil {
		return x.CardName
	}
	return ""
}

func (x *TransferSnapshot) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *TransferSnapshot) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *TransferSnapshot) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *TransferSnapshot) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *TransferSnapshot) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *TransferSnapshot) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *TransferSnapshot) GetNotify() int32 {
	if x != nil {
		return x.Notify
	}
	return 0
}

func (x *TransferSnapshot) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TransferSnapshot) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TransferSnapshot) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TransferSnapshot) GetEndtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Endtime
	}
	return nil
}

func (x *TransferSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransferSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ChannelSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Plugin        string                 `protobuf:"bytes,3,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Rate          string                 `protobuf:"bytes,5,opt,name=rate,proto3" json:"rate,omitempty"`
	FixedFee      int64                  `protobuf:"varint,6,opt,name=fixed_fee,json=fixedFee,proto3" json:"fixed_fee,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Action        int32                  `protobuf:"varint,8,opt,name=action,proto3" json:"action,omitempty"`
	Domain        string                 `protobuf:"bytes,9,opt,name=domain,proto3" json:"domain,omitempty"`
	ConfigJsonRaw []byte                 `protobuf:"bytes,10,opt,name=config_json_raw,json=configJsonRaw,proto3" json:"config_json_raw,omitempty"`
	Daylimit      int64                  `protobuf:"varint,11,opt,name=daylimit,proto3" json:"daylimit,omitempty"`
	Daynumber     int64                  `protobuf:"varint,12,opt,name=daynumber,proto3" json:"daynumber,omitempty"`
	Paymin        int64                  `protobuf:"varint,13,opt,name=paymin,proto3" json:"paymin,omitempty"`
	Paymax        int64                  `protobuf:"varint,14,opt,name=paymax,proto3" json:"paymax,omitempty"`
	Author        int64                  `protobuf:"varint,15,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelSnapshot) Reset() {
	*x = ChannelSnapshot{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSnapshot) ProtoMessage() {}

func (x *ChannelSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSnapshot.ProtoReflect.Descriptor instead.
func (*ChannelSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelSnapshot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChannelSnapshot) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ChannelSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelSnapshot) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *ChannelSnapshot) GetFixedFee() int64 {
	if x != nil {
		return x.FixedFee
	}
	return 0
}

func (x *ChannelSnapshot) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChannelSnapshot) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *ChannelSnapshot) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ChannelSnapshot) GetConfigJsonRaw() []byte {
	if x != nil {
		return x.ConfigJsonRaw
	}
	return nil
}

func (x *ChannelSnapshot) GetDaylimit() int64 {
	if x != nil {
		return x.Daylimit
	}
	return 0
}

func (x *ChannelSnapshot) GetDaynumber() int64 {
	if x != nil {
		return x.Daynumber
	}
	return 0
}

func (x *ChannelSnapshot) GetPaymin() int64 {
	if x != nil {
		return x.Paymin
	}
	return 0
}

func (x *ChannelSnapshot) GetPaymax() int64 {
	if x != nil {
		return x.Paymax
	}
	return 0
}

func (x *ChannelSnapshot) GetAuthor() int64 {
	if x != nil {
		return x.Author
	}
	return 0
}

func (x *ChannelSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChannelSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ConfigSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteDomain    string                 `protobuf:"bytes,1,opt,name=site_domain,json=siteDomain,proto3" json:"site_domain,omitempty"`
	NotifyDomain  string                 `protobuf:"bytes,2,opt,name=notify_domain,json=notifyDomain,proto3" json:"notify_domain,omitempty"`
	Localhost     string                 `protobuf:"bytes,3,opt,name=localhost,proto3" json:"localhost,omitempty"`
	GoodsName     string                 `protobuf:"bytes,4,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	CreateTimeout string                 `protobuf:"bytes,5,opt,name=create_timeout,json=createTimeout,proto3" json:"create_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigSnapshot) GetSiteDomain() string {
	if x != nil {
		return x.SiteDomain
	}
	return ""
}

func (x *ConfigSnapshot) GetNotifyDomain() string {
	if x != nil {
		return x.NotifyDomain
	}
	return ""
}

func (x *ConfigSnapshot) GetLocalhost() string {
	if x != nil {
		return x.Localhost
	}
	return ""
}

func (x *ConfigSnapshot) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *ConfigSnapshot) GetCreateTimeout() string {
	if x != nil {
		return x.CreateTimeout
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Ua            string                 `protobuf:"bytes,4,opt,name=ua,proto3" json:"ua,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Headers       []*HeaderKV            `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Request) GetUa() string {
	if x != nil {
		return x.Ua
	}
	return ""
}

func (x *Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetHeaders() []*HeaderKV {
	if x != nil {
		return x.Headers
	}
	return nil
}

type InvokeContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Action         string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	FuncName       string                 `protobuf:"bytes,3,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	TradeNo        string                 `protobuf:"bytes,4,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	Order          *OrderSnapshot         `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	Refund         *RefundSnapshot        `protobuf:"bytes,6,opt,name=refund,proto3" json:"refund,omitempty"`
	Transfer       *TransferSnapshot      `protobuf:"bytes,7,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Channel        *ChannelSnapshot       `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	Config         *ConfigSnapshot        `protobuf:"bytes,9,opt,name=config,proto3" json:"config,omitempty"`
	Request        *Request               `protobuf:"bytes,10,opt,name=request,proto3" json:"request,omitempty"`
	KernelBrokerId uint32                 `protobuf:"varint,11,opt,name=kernel_broker_id,json=kernelBrokerId,proto3" json:"kernel_broker_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvokeContext) Reset() {
	*x = InvokeContext{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeContext) ProtoMessage() {}

func (x *InvokeContext) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeContext.ProtoReflect.Descriptor instead.
func (*InvokeContext) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeContext) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InvokeContext) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *InvokeContext) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *InvokeContext) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *InvokeContext) GetRefund() *RefundSnapshot {
	if x != nil {
		return x.Refund
	}
	return nil
}

func (x *InvokeContext) GetTransfer() *TransferSnapshot {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *InvokeContext) GetChannel() *ChannelSnapshot {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *InvokeContext) GetConfig() *ConfigSnapshot {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InvokeContext) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *InvokeContext) GetKernelBrokerId() uint32 {
	if x != nil {
		return x.KernelBrokerId
	}
	return 0
}

type PluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfoRequest) Reset() {
	*x = PluginInfoRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoRequest) ProtoMessage() {}

func (x *PluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoRequest.ProtoReflect.Descriptor instead.
func (*PluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

type InputField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputField) Reset() {
	*x = InputField{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputField) ProtoMessage() {}

func (x *InputField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputField.ProtoReflect.Descriptor instead.
func (*InputField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *InputField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InputField) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *InputField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *InputField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *InputField) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type PluginInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Paytypes      []string               `protobuf:"bytes,4,rep,name=paytypes,proto3" json:"paytypes,omitempty"`
	Transtypes    []string               `protobuf:"bytes,5,rep,name=transtypes,proto3" json:"transtypes,omitempty"`
	Inputs        map[string]*InputField `protobuf:"bytes,6,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Note          string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfoResponse) Reset() {
	*x = PluginInfoResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoResponse) ProtoMessage() {}

func (x *PluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoResponse.ProtoReflect.Descriptor instead.
func (*PluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *PluginInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfoResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PluginInfoResponse) GetPaytypes() []string {
	if x != nil {
		return x.Paytypes
	}
	return nil
}

func (x *PluginInfoResponse) GetTranstypes() []string {
	if x != nil {
		return x.Transtypes
	}
	return nil
}

func (x *PluginInfoResponse) GetInputs() map[string]*InputField {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *PluginInfoResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Page          string                 `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	DataJsonRaw   []byte                 `protobuf:"bytes,5,opt,name=data_json_raw,json=dataJsonRaw,proto3" json:"data_json_raw,omitempty"`
	DataText      string                 `protobuf:"bytes,6,opt,name=data_text,json=dataText,proto3" json:"data_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PageResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PageResponse) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *PageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PageResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PageResponse) GetDataJsonRaw() []byte {
	if x != nil {
		return x.DataJsonRaw
	}
	return nil
}

func (x *PageResponse) GetDataText() string {
	if x != nil {
		return x.DataText
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *InvokeContext         `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRequest) GetCtx() *InvokeContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResponse          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *CreateResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *InvokeContext         `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *QueryRequest) GetCtx() *InvokeContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         int32                  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	ApiTradeNo    string                 `protobuf:"bytes,2,opt,name=api_trade_no,json=apiTradeNo,proto3" json:"api_trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *QueryResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *QueryResponse) GetApiTradeNo() string {
	if x != nil {
		return x.ApiTradeNo
	}
	return ""
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *InvokeContext         `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *RefundRequest) GetCtx() *InvokeContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         int32                  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	ApiRefundNo   string                 `protobuf:"bytes,2,opt,name=api_refund_no,json=apiRefundNo,proto3" json:"api_refund_no,omitempty"`
	ReqMs         int32                  `protobuf:"varint,3,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ReqBody       string                 `protobuf:"bytes,4,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,5,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *RefundResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *RefundResponse) GetApiRefundNo() string {
	if x != nil {
		return x.ApiRefundNo
	}
	return ""
}

func (x *RefundResponse) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *RefundResponse) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *RefundResponse) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *RefundResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *InvokeContext         `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *TransferRequest) GetCtx() *InvokeContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         int32                  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	ApiTradeNo    string                 `protobuf:"bytes,2,opt,name=api_trade_no,json=apiTradeNo,proto3" json:"api_trade_no,omitempty"`
	ReqMs         int32                  `protobuf:"varint,3,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ReqBody       string                 `protobuf:"bytes,4,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,5,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *TransferResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *TransferResponse) GetApiTradeNo() string {
	if x != nil {
		return x.ApiTradeNo
	}
	return ""
}

func (x *TransferResponse) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *TransferResponse) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *TransferResponse) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *TransferResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *InvokeContext         `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *BalanceRequest) GetCtx() *InvokeContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *BalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type InvokeFuncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *InvokeContext         `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeFuncRequest) Reset() {
	*x = InvokeFuncRequest{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeFuncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeFuncRequest) ProtoMessage() {}

func (x *InvokeFuncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeFuncRequest.ProtoReflect.Descriptor instead.
func (*InvokeFuncRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *InvokeFuncRequest) GetCtx() *InvokeContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type InvokeFuncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResponse          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeFuncResponse) Reset() {
	*x = InvokeFuncResponse{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeFuncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeFuncResponse) ProtoMessage() {}

func (x *InvokeFuncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeFuncResponse.ProtoReflect.Descriptor instead.
func (*InvokeFuncResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *InvokeFuncResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type PluginError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginError) Reset() {
	*x = PluginError{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginError) ProtoMessage() {}

func (x *PluginError) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginError.ProtoReflect.Descriptor instead.
func (*PluginError) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *PluginError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PluginError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error         *PluginError           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *Ack) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Ack) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Ack) GetError() *PluginError {
	if x != nil {
		return x.Error
	}
	return nil
}

type CompleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	TradeNo       string                 `protobuf:"bytes,3,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	ApiTradeNo    string                 `protobuf:"bytes,4,opt,name=api_trade_no,json=apiTradeNo,proto3" json:"api_trade_no,omitempty"`
	Buyer         string                 `protobuf:"bytes,5,opt,name=buyer,proto3" json:"buyer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderRequest) Reset() {
	*x = CompleteOrderRequest{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderRequest) ProtoMessage() {}

func (x *CompleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderRequest.ProtoReflect.Descriptor instead.
func (*CompleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *CompleteOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompleteOrderRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *CompleteOrderRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *CompleteOrderRequest) GetApiTradeNo() string {
	if x != nil {
		return x.ApiTradeNo
	}
	return ""
}

func (x *CompleteOrderRequest) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

type CompleteRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	RefundNo      string                 `protobuf:"bytes,3,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	ApiRefundNo   string                 `protobuf:"bytes,5,opt,name=api_refund_no,json=apiRefundNo,proto3" json:"api_refund_no,omitempty"`
	RespBody      string                 `protobuf:"bytes,6,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRefundRequest) Reset() {
	*x = CompleteRefundRequest{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRefundRequest) ProtoMessage() {}

func (x *CompleteRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRefundRequest.ProtoReflect.Descriptor instead.
func (*CompleteRefundRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *CompleteRefundRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompleteRefundRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *CompleteRefundRequest) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *CompleteRefundRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CompleteRefundRequest) GetApiRefundNo() string {
	if x != nil {
		return x.ApiRefundNo
	}
	return ""
}

func (x *CompleteRefundRequest) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

type CompleteTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	TradeNo       string                 `protobuf:"bytes,3,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	ApiTradeNo    string                 `protobuf:"bytes,5,opt,name=api_trade_no,json=apiTradeNo,proto3" json:"api_trade_no,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTransferRequest) Reset() {
	*x = CompleteTransferRequest{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTransferRequest) ProtoMessage() {}

func (x *CompleteTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTransferRequest.ProtoReflect.Descriptor instead.
func (*CompleteTransferRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *CompleteTransferRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompleteTransferRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *CompleteTransferRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *CompleteTransferRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CompleteTransferRequest) GetApiTradeNo() string {
	if x != nil {
		return x.ApiTradeNo
	}
	return ""
}

func (x *CompleteTransferRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RecordCNotifyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PluginId        string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	BizType         string                 `protobuf:"bytes,3,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	TradeNo         string                 `protobuf:"bytes,4,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	RequestIp       string                 `protobuf:"bytes,5,opt,name=request_ip,json=requestIp,proto3" json:"request_ip,omitempty"`
	RequestUrl      string                 `protobuf:"bytes,6,opt,name=request_url,json=requestUrl,proto3" json:"request_url,omitempty"`
	RequestBodyRaw  []byte                 `protobuf:"bytes,7,opt,name=request_body_raw,json=requestBodyRaw,proto3" json:"request_body_raw,omitempty"`
	ResponseBodyRaw []byte                 `protobuf:"bytes,8,opt,name=response_body_raw,json=responseBodyRaw,proto3" json:"response_body_raw,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecordCNotifyRequest) Reset() {
	*x = RecordCNotifyRequest{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordCNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCNotifyRequest) ProtoMessage() {}

func (x *RecordCNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCNotifyRequest.ProtoReflect.Descriptor instead.
func (*RecordCNotifyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *RecordCNotifyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecordCNotifyRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *RecordCNotifyRequest) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *RecordCNotifyRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RecordCNotifyRequest) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

func (x *RecordCNotifyRequest) GetRequestUrl() string {
	if x != nil {
		return x.RequestUrl
	}
	return ""
}

func (x *RecordCNotifyRequest) GetRequestBodyRaw() []byte {
	if x != nil {
		return x.RequestBodyRaw
	}
	return nil
}

func (x *RecordCNotifyRequest) GetResponseBodyRaw() []byte {
	if x != nil {
		return x.ResponseBodyRaw
	}
	return nil
}

type LockOrderExtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	TradeNo       string                 `protobuf:"bytes,3,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	ReqBody       string                 `protobuf:"bytes,4,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,5,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	ReqCount      int32                  `protobuf:"varint,6,opt,name=req_count,json=reqCount,proto3" json:"req_count,omitempty"`
	ReqMs         int32                  `protobuf:"varint,7,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ExtJsonRaw    []byte                 `protobuf:"bytes,8,opt,name=ext_json_raw,json=extJsonRaw,proto3" json:"ext_json_raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockOrderExtRequest) Reset() {
	*x = LockOrderExtRequest{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockOrderExtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockOrderExtRequest) ProtoMessage() {}

func (x *LockOrderExtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockOrderExtRequest.ProtoReflect.Descriptor instead.
func (*LockOrderExtRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *LockOrderExtRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LockOrderExtRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *LockOrderExtRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *LockOrderExtRequest) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *LockOrderExtRequest) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *LockOrderExtRequest) GetReqCount() int32 {
	if x != nil {
		return x.ReqCount
	}
	return 0
}

func (x *LockOrderExtRequest) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *LockOrderExtRequest) GetExtJsonRaw() []byte {
	if x != nil {
		return x.ExtJsonRaw
	}
	return nil
}

type LockOrderExtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtJsonRaw    []byte                 `protobuf:"bytes,1,opt,name=ext_json_raw,json=extJsonRaw,proto3" json:"ext_json_raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockOrderExtResponse) Reset() {
	*x = LockOrderExtResponse{}
	mi := &file_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockOrderExtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockOrderExtResponse) ProtoMessage() {}

func (x *LockOrderExtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockOrderExtResponse.ProtoReflect.Descriptor instead.
func (*LockOrderExtResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *LockOrderExtResponse) GetExtJsonRaw() []byte {
	if x != nil {
		return x.ExtJsonRaw
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\fokpay.plugin\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\bHeaderKV\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x82\a\n" +
	"\rOrderSnapshot\x12\x19\n" +
	"\btrade_no\x18\x01 \x01(\tR\atradeNo\x12 \n" +
	"\fout_trade_no\x18\x02 \x01(\tR\n" +
	"outTradeNo\x12 \n" +
	"\fapi_trade_no\x18\x03 \x01(\tR\n" +
	"apiTradeNo\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06plugin\x18\x06 \x01(\tR\x06plugin\x12\x18\n" +
	"\achannel\x18\a \x01(\x03R\achannel\x12\x10\n" +
	"\x03cid\x18\b \x01(\x03R\x03cid\x12\x12\n" +
	"\x04code\x18\t \x01(\x03R\x04code\x12\x18\n" +
	"\asubject\x18\n" +
	" \x01(\tR\asubject\x12\x16\n" +
	"\x06amount\x18\v \x01(\x03R\x06amount\x12\x12\n" +
	"\x04real\x18\f \x01(\x03R\x04real\x12\x10\n" +
	"\x03fee\x18\r \x01(\x03R\x03fee\x12\x10\n" +
	"\x03get\x18\x0e \x01(\x03R\x03get\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x0f \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\x10 \x01(\tR\treturnUrl\x12\x14\n" +
	"\x05param\x18\x11 \x01(\tR\x05param\x12\x16\n" +
	"\x06domain\x18\x12 \x01(\tR\x06domain\x12\x19\n" +
	"\bip_buyer\x18\x13 \x01(\tR\aipBuyer\x12\x1b\n" +
	"\tip_source\x18\x14 \x01(\tR\bipSource\x12\x14\n" +
	"\x05buyer\x18\x15 \x01(\tR\x05buyer\x12\x16\n" +
	"\x06status\x18\x16 \x01(\x05R\x06status\x12\x16\n" +
	"\x06notify\x18\x17 \x01(\x05R\x06notify\x12\x15\n" +
	"\x06req_ms\x18\x18 \x01(\x05R\x05reqMs\x12\x1b\n" +
	"\treq_count\x18\x19 \x01(\x05R\breqCount\x12\x19\n" +
	"\breq_body\x18\x1a \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\x1b \x01(\tR\brespBody\x12\x10\n" +
	"\x03ext\x18\x1c \x01(\tR\x03ext\x12\x16\n" +
	"\x06result\x18\x1d \x01(\tR\x06result\x124\n" +
	"\aendtime\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\aendtime\x129\n" +
	"\n" +
	"created_at\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18  \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe0\x04\n" +
	"\x0eRefundSnapshot\x12\x1b\n" +
	"\trefund_no\x18\x01 \x01(\tR\brefundNo\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\x12\"\n" +
	"\rout_refund_no\x18\x03 \x01(\tR\voutRefundNo\x12\"\n" +
	"\rapi_refund_no\x18\x04 \x01(\tR\vapiRefundNo\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\x03R\x03uid\x12\x18\n" +
	"\achannel\x18\x06 \x01(\x03R\achannel\x12\x10\n" +
	"\x03cid\x18\a \x01(\x03R\x03cid\x12\x16\n" +
	"\x06amount\x18\b \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"notify_url\x18\t \x01(\tR\tnotifyUrl\x12\x15\n" +
	"\x06req_ms\x18\n" +
	" \x01(\x05R\x05reqMs\x12\x19\n" +
	"\breq_body\x18\v \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\f \x01(\tR\brespBody\x12\x16\n" +
	"\x06notify\x18\r \x01(\x05R\x06notify\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x0f \x01(\tR\x06remark\x12\x16\n" +
	"\x06result\x18\x10 \x01(\tR\x06result\x124\n" +
	"\aendtime\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\aendtime\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x06\n" +
	"\x10TransferSnapshot\x12\x19\n" +
	"\btrade_no\x18\x01 \x01(\tR\atradeNo\x12 \n" +
	"\fapi_trade_no\x18\x02 \x01(\tR\n" +
	"apiTradeNo\x12 \n" +
	"\fout_trade_no\x18\x03 \x01(\tR\n" +
	"outTradeNo\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bbusiness\x18\x05 \x01(\x05R\bbusiness\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x18\n" +
	"\achannel\x18\a \x01(\x03R\achannel\x12\x10\n" +
	"\x03cid\x18\b \x01(\x03R\x03cid\x12\x12\n" +
	"\x04code\x18\t \x01(\x03R\x04code\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x03R\x06amount\x12\x10\n" +
	"\x03fee\x18\v \x01(\x03R\x03fee\x12\x12\n" +
	"\x04cost\x18\f \x01(\x03R\x04cost\x12\x1b\n" +
	"\tbank_name\x18\r \x01(\tR\bbankName\x12\x1b\n" +
	"\tcard_name\x18\x0e \x01(\tR\bcardName\x12\x17\n" +
	"\acard_no\x18\x0f \x01(\tR\x06cardNo\x12\x1f\n" +
	"\vbranch_name\x18\x10 \x01(\tR\n" +
	"branchName\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x11 \x01(\tR\tnotifyUrl\x12\x15\n" +
	"\x06req_ms\x18\x12 \x01(\x05R\x05reqMs\x12\x19\n" +
	"\breq_body\x18\x13 \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\x14 \x01(\tR\brespBody\x12\x16\n" +
	"\x06notify\x18\x15 \x01(\x05R\x06notify\x12\x16\n" +
	"\x06status\x18\x16 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x17 \x01(\tR\x06remark\x12\x16\n" +
	"\x06result\x18\x18 \x01(\tR\x06result\x124\n" +
	"\aendtime\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\aendtime\x129\n" +
	"\n" +
	"created_at\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfa\x03\n" +
	"\x0fChannelSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06plugin\x18\x03 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\tR\x04rate\x12\x1b\n" +
	"\tfixed_fee\x18\x06 \x01(\x03R\bfixedFee\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x16\n" +
	"\x06action\x18\b \x01(\x05R\x06action\x12\x16\n" +
	"\x06domain\x18\t \x01(\tR\x06domain\x12&\n" +
	"\x0fconfig_json_raw\x18\n" +
	" \x01(\fR\rconfigJsonRaw\x12\x1a\n" +
	"\bdaylimit\x18\v \x01(\x03R\bdaylimit\x12\x1c\n" +
	"\tdaynumber\x18\f \x01(\x03R\tdaynumber\x12\x16\n" +
	"\x06paymin\x18\r \x01(\x03R\x06paymin\x12\x16\n" +
	"\x06paymax\x18\x0e \x01(\x03R\x06paymax\x12\x16\n" +
	"\x06author\x18\x0f \x01(\x03R\x06author\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc0\x01\n" +
	"\x0eConfigSnapshot\x12\x1f\n" +
	"\vsite_domain\x18\x01 \x01(\tR\n" +
	"siteDomain\x12#\n" +
	"\rnotify_domain\x18\x02 \x01(\tR\fnotifyDomain\x12\x1c\n" +
	"\tlocalhost\x18\x03 \x01(\tR\tlocalhost\x12\x1d\n" +
	"\n" +
	"goods_name\x18\x04 \x01(\tR\tgoodsName\x12%\n" +
	"\x0ecreate_timeout\x18\x05 \x01(\tR\rcreateTimeoutJ\x04\b\x06\x10\a\"\xb5\x01\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02ua\x18\x04 \x01(\tR\x02ua\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x120\n" +
	"\aheaders\x18\a \x03(\v2\x16.okpay.plugin.HeaderKVR\aheadersJ\x04\b\b\x10\v\"\xed\x03\n" +
	"\rInvokeContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1b\n" +
	"\tfunc_name\x18\x03 \x01(\tR\bfuncName\x12\x19\n" +
	"\btrade_no\x18\x04 \x01(\tR\atradeNo\x121\n" +
	"\x05order\x18\x05 \x01(\v2\x1b.okpay.plugin.OrderSnapshotR\x05order\x124\n" +
	"\x06refund\x18\x06 \x01(\v2\x1c.okpay.plugin.RefundSnapshotR\x06refund\x12:\n" +
	"\btransfer\x18\a \x01(\v2\x1e.okpay.plugin.TransferSnapshotR\btransfer\x127\n" +
	"\achannel\x18\b \x01(\v2\x1d.okpay.plugin.ChannelSnapshotR\achannel\x124\n" +
	"\x06config\x18\t \x01(\v2\x1c.okpay.plugin.ConfigSnapshotR\x06config\x12/\n" +
	"\arequest\x18\n" +
	" \x01(\v2\x15.okpay.plugin.RequestR\arequest\x12(\n" +
	"\x10kernel_broker_id\x18\v \x01(\rR\x0ekernelBrokerId\"\x13\n" +
	"\x11PluginInfoRequest\"\x86\x02\n" +
	"\n" +
	"InputField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\x12?\n" +
	"\aoptions\x18\x06 \x03(\v2%.okpay.plugin.InputField.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x02\n" +
	"\x12PluginInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1a\n" +
	"\bpaytypes\x18\x04 \x03(\tR\bpaytypes\x12\x1e\n" +
	"\n" +
	"transtypes\x18\x05 \x03(\tR\n" +
	"transtypes\x12D\n" +
	"\x06inputs\x18\x06 \x03(\v2,.okpay.plugin.PluginInfoResponse.InputsEntryR\x06inputs\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x1aS\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.okpay.plugin.InputFieldR\x05value:\x028\x01\"\x9b\x01\n" +
	"\fPageResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04page\x18\x02 \x01(\tR\x04page\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\"\n" +
	"\rdata_json_raw\x18\x05 \x01(\fR\vdataJsonRaw\x12\x1b\n" +
	"\tdata_text\x18\x06 \x01(\tR\bdataText\">\n" +
	"\rCreateRequest\x12-\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1b.okpay.plugin.InvokeContextR\x03ctx\"@\n" +
	"\x0eCreateResponse\x12.\n" +
	"\x04page\x18\x01 \x01(\v2\x1a.okpay.plugin.PageResponseR\x04page\"=\n" +
	"\fQueryRequest\x12-\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1b.okpay.plugin.InvokeContextR\x03ctx\"G\n" +
	"\rQueryResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x05R\x05state\x12 \n" +
	"\fapi_trade_no\x18\x02 \x01(\tR\n" +
	"apiTradeNo\">\n" +
	"\rRefundRequest\x12-\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1b.okpay.plugin.InvokeContextR\x03ctx\"\xb1\x01\n" +
	"\x0eRefundResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x05R\x05state\x12\"\n" +
	"\rapi_refund_no\x18\x02 \x01(\tR\vapiRefundNo\x12\x15\n" +
	"\x06req_ms\x18\x03 \x01(\x05R\x05reqMs\x12\x19\n" +
	"\breq_body\x18\x04 \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\x05 \x01(\tR\brespBody\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\"@\n" +
	"\x0fTransferRequest\x12-\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1b.okpay.plugin.InvokeContextR\x03ctx\"\xb1\x01\n" +
	"\x10TransferResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x05R\x05state\x12 \n" +
	"\fapi_trade_no\x18\x02 \x01(\tR\n" +
	"apiTradeNo\x12\x15\n" +
	"\x06req_ms\x18\x03 \x01(\x05R\x05reqMs\x12\x19\n" +
	"\breq_body\x18\x04 \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\x05 \x01(\tR\brespBody\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\"?\n" +
	"\x0eBalanceRequest\x12-\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1b.okpay.plugin.InvokeContextR\x03ctx\"+\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance\"B\n" +
	"\x11InvokeFuncRequest\x12-\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1b.okpay.plugin.InvokeContextR\x03ctx\"D\n" +
	"\x12InvokeFuncResponse\x12.\n" +
	"\x04page\x18\x01 \x01(\v2\x1a.okpay.plugin.PageResponseR\x04page\"Y\n" +
	"\vPluginError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"q\n" +
	"\x03Ack\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.okpay.plugin.PluginErrorR\x05error\"\xa5\x01\n" +
	"\x14CompleteOrderRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x19\n" +
	"\btrade_no\x18\x03 \x01(\tR\atradeNo\x12 \n" +
	"\fapi_trade_no\x18\x04 \x01(\tR\n" +
	"apiTradeNo\x12\x14\n" +
	"\x05buyer\x18\x05 \x01(\tR\x05buyer\"\xc9\x01\n" +
	"\x15CompleteRefundRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x1b\n" +
	"\trefund_no\x18\x03 \x01(\tR\brefundNo\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\"\n" +
	"\rapi_refund_no\x18\x05 \x01(\tR\vapiRefundNo\x12\x1b\n" +
	"\tresp_body\x18\x06 \x01(\tR\brespBody\"\xc2\x01\n" +
	"\x17CompleteTransferRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x19\n" +
	"\btrade_no\x18\x03 \x01(\tR\atradeNo\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12 \n" +
	"\fapi_trade_no\x18\x05 \x01(\tR\n" +
	"apiTradeNo\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\"\x9e\x02\n" +
	"\x14RecordCNotifyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x19\n" +
	"\bbiz_type\x18\x03 \x01(\tR\abizType\x12\x19\n" +
	"\btrade_no\x18\x04 \x01(\tR\atradeNo\x12\x1d\n" +
	"\n" +
	"request_ip\x18\x05 \x01(\tR\trequestIp\x12\x1f\n" +
	"\vrequest_url\x18\x06 \x01(\tR\n" +
	"requestUrl\x12(\n" +
	"\x10request_body_raw\x18\a \x01(\fR\x0erequestBodyRaw\x12*\n" +
	"\x11response_body_raw\x18\b \x01(\fR\x0fresponseBodyRaw\"\xfa\x01\n" +
	"\x13LockOrderExtRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x19\n" +
	"\btrade_no\x18\x03 \x01(\tR\atradeNo\x12\x19\n" +
	"\breq_body\x18\x04 \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\x05 \x01(\tR\brespBody\x12\x1b\n" +
	"\treq_count\x18\x06 \x01(\x05R\breqCount\x12\x15\n" +
	"\x06req_ms\x18\a \x01(\x05R\x05reqMs\x12 \n" +
	"\fext_json_raw\x18\b \x01(\fR\n" +
	"extJsonRaw\"8\n" +
	"\x14LockOrderExtResponse\x12 \n" +
	"\fext_json_raw\x18\x01 \x01(\fR\n" +
	"extJsonRaw2\x8a\x04\n" +
	"\rPluginService\x12I\n" +
	"\x04Info\x12\x1f.okpay.plugin.PluginInfoRequest\x1a .okpay.plugin.PluginInfoResponse\x12C\n" +
	"\x06Create\x12\x1b.okpay.plugin.CreateRequest\x1a\x1c.okpay.plugin.CreateResponse\x12@\n" +
	"\x05Query\x12\x1a.okpay.plugin.QueryRequest\x1a\x1b.okpay.plugin.QueryResponse\x12C\n" +
	"\x06Refund\x12\x1b.okpay.plugin.RefundRequest\x1a\x1c.okpay.plugin.RefundResponse\x12I\n" +
	"\bTransfer\x12\x1d.okpay.plugin.TransferRequest\x1a\x1e.okpay.plugin.TransferResponse\x12F\n" +
	"\aBalance\x12\x1c.okpay.plugin.BalanceRequest\x1a\x1d.okpay.plugin.BalanceResponse\x12O\n" +
	"\n" +
	"InvokeFunc\x12\x1f.okpay.plugin.InvokeFuncRequest\x1a .okpay.plugin.InvokeFuncResponse2\x8e\x03\n" +
	"\rKernelService\x12F\n" +
	"\rCompleteOrder\x12\".okpay.plugin.CompleteOrderRequest\x1a\x11.okpay.plugin.Ack\x12H\n" +
	"\x0eCompleteRefund\x12#.okpay.plugin.CompleteRefundRequest\x1a\x11.okpay.plugin.Ack\x12L\n" +
	"\x10CompleteTransfer\x12%.okpay.plugin.CompleteTransferRequest\x1a\x11.okpay.plugin.Ack\x12F\n" +
	"\rRecordCNotify\x12\".okpay.plugin.RecordCNotifyRequest\x1a\x11.okpay.plugin.Ack\x12U\n" +
	"\fLockOrderExt\x12!.okpay.plugin.LockOrderExtRequest\x1a\".okpay.plugin.LockOrderExtResponseB\"Z okpay/payment/plugin/proto;protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_plugin_proto_goTypes = []any{
	(*HeaderKV)(nil),                // 0: okpay.plugin.HeaderKV
	(*OrderSnapshot)(nil),           // 1: okpay.plugin.OrderSnapshot
	(*RefundSnapshot)(nil),          // 2: okpay.plugin.RefundSnapshot
	(*TransferSnapshot)(nil),        // 3: okpay.plugin.TransferSnapshot
	(*ChannelSnapshot)(nil),         // 4: okpay.plugin.ChannelSnapshot
	(*ConfigSnapshot)(nil),          // 5: okpay.plugin.ConfigSnapshot
	(*Request)(nil),                 // 6: okpay.plugin.Request
	(*InvokeContext)(nil),           // 7: okpay.plugin.InvokeContext
	(*PluginInfoRequest)(nil),       // 8: okpay.plugin.PluginInfoRequest
	(*InputField)(nil),              // 9: okpay.plugin.InputField
	(*PluginInfoResponse)(nil),      // 10: okpay.plugin.PluginInfoResponse
	(*PageResponse)(nil),            // 11: okpay.plugin.PageResponse
	(*CreateRequest)(nil),           // 12: okpay.plugin.CreateRequest
	(*CreateResponse)(nil),          // 13: okpay.plugin.CreateResponse
	(*QueryRequest)(nil),            // 14: okpay.plugin.QueryRequest
	(*QueryResponse)(nil),           // 15: okpay.plugin.QueryResponse
	(*RefundRequest)(nil),           // 16: okpay.plugin.RefundRequest
	(*RefundResponse)(nil),          // 17: okpay.plugin.RefundResponse
	(*TransferRequest)(nil),         // 18: okpay.plugin.TransferRequest
	(*TransferResponse)(nil),        // 19: okpay.plugin.TransferResponse
	(*BalanceRequest)(nil),          // 20: okpay.plugin.BalanceRequest
	(*BalanceResponse)(nil),         // 21: okpay.plugin.BalanceResponse
	(*InvokeFuncRequest)(nil),       // 22: okpay.plugin.InvokeFuncRequest
	(*InvokeFuncResponse)(nil),      // 23: okpay.plugin.InvokeFuncResponse
	(*PluginError)(nil),             // 24: okpay.plugin.PluginError
	(*Ack)(nil),                     // 25: okpay.plugin.Ack
	(*CompleteOrderRequest)(nil),    // 26: okpay.plugin.CompleteOrderRequest
	(*CompleteRefundRequest)(nil),   // 27: okpay.plugin.CompleteRefundRequest
	(*CompleteTransferRequest)(nil), // 28: okpay.plugin.CompleteTransferRequest
	(*RecordCNotifyRequest)(nil),    // 29: okpay.plugin.RecordCNotifyRequest
	(*LockOrderExtRequest)(nil),     // 30: okpay.plugin.LockOrderExtRequest
	(*LockOrderExtResponse)(nil),    // 31: okpay.plugin.LockOrderExtResponse
	nil,                             // 32: okpay.plugin.InputField.OptionsEntry
	nil,                             // 33: okpay.plugin.PluginInfoResponse.InputsEntry
	(*timestamppb.Timestamp)(nil),   // 34: google.protobuf.Timestamp
}
var file_plugin_proto_depIdxs = []int32{
	34, // 0: okpay.plugin.OrderSnapshot.endtime:type_name -> google.protobuf.Timestamp
	34, // 1: okpay.plugin.OrderSnapshot.created_at:type_name -> google.protobuf.Timestamp
	34, // 2: okpay.plugin.OrderSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	34, // 3: okpay.plugin.RefundSnapshot.endtime:type_name -> google.protobuf.Timestamp
	34, // 4: okpay.plugin.RefundSnapshot.created_at:type_name -> google.protobuf.Timestamp
	34, // 5: okpay.plugin.RefundSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	34, // 6: okpay.plugin.TransferSnapshot.endtime:type_name -> google.protobuf.Timestamp
	34, // 7: okpay.plugin.TransferSnapshot.created_at:type_name -> google.protobuf.Timestamp
	34, // 8: okpay.plugin.TransferSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	34, // 9: okpay.plugin.ChannelSnapshot.created_at:type_name -> google.protobuf.Timestamp
	34, // 10: okpay.plugin.ChannelSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: okpay.plugin.Request.headers:type_name -> okpay.plugin.HeaderKV
	1,  // 12: okpay.plugin.InvokeContext.order:type_name -> okpay.plugin.OrderSnapshot
	2,  // 13: okpay.plugin.InvokeContext.refund:type_name -> okpay.plugin.RefundSnapshot
	3,  // 14: okpay.plugin.InvokeContext.transfer:type_name -> okpay.plugin.TransferSnapshot
	4,  // 15: okpay.plugin.InvokeContext.channel:type_name -> okpay.plugin.ChannelSnapshot
	5,  // 16: okpay.plugin.InvokeContext.config:type_name -> okpay.plugin.ConfigSnapshot
	6,  // 17: okpay.plugin.InvokeContext.request:type_name -> okpay.plugin.Request
	32, // 18: okpay.plugin.InputField.options:type_name -> okpay.plugin.InputField.OptionsEntry
	33, // 19: okpay.plugin.PluginInfoResponse.inputs:type_name -> okpay.plugin.PluginInfoResponse.InputsEntry
	7,  // 20: okpay.plugin.CreateRequest.ctx:type_name -> okpay.plugin.InvokeContext
	11, // 21: okpay.plugin.CreateResponse.page:type_name -> okpay.plugin.PageResponse
	7,  // 22: okpay.plugin.QueryRequest.ctx:type_name -> okpay.plugin.InvokeContext
	7,  // 23: okpay.plugin.RefundRequest.ctx:type_name -> okpay.plugin.InvokeContext
	7,  // 24: okpay.plugin.TransferRequest.ctx:type_name -> okpay.plugin.InvokeContext
	7,  // 25: okpay.plugin.BalanceRequest.ctx:type_name -> okpay.plugin.InvokeContext
	7,  // 26: okpay.plugin.InvokeFuncRequest.ctx:type_name -> okpay.plugin.InvokeContext
	11, // 27: okpay.plugin.InvokeFuncResponse.page:type_name -> okpay.plugin.PageResponse
	24, // 28: okpay.plugin.Ack.error:type_name -> okpay.plugin.PluginError
	9,  // 29: okpay.plugin.PluginInfoResponse.InputsEntry.value:type_name -> okpay.plugin.InputField
	8,  // 30: okpay.plugin.PluginService.Info:input_type -> okpay.plugin.PluginInfoRequest
	12, // 31: okpay.plugin.PluginService.Create:input_type -> okpay.plugin.CreateRequest
	14, // 32: okpay.plugin.PluginService.Query:input_type -> okpay.plugin.QueryRequest
	16, // 33: okpay.plugin.PluginService.Refund:input_type -> okpay.plugin.RefundRequest
	18, // 34: okpay.plugin.PluginService.Transfer:input_type -> okpay.plugin.TransferRequest
	20, // 35: okpay.plugin.PluginService.Balance:input_type -> okpay.plugin.BalanceRequest
	22, // 36: okpay.plugin.PluginService.InvokeFunc:input_type -> okpay.plugin.InvokeFuncRequest
	26, // 37: okpay.plugin.KernelService.CompleteOrder:input_type -> okpay.plugin.CompleteOrderRequest
	27, // 38: okpay.plugin.KernelService.CompleteRefund:input_type -> okpay.plugin.CompleteRefundRequest
	28, // 39: okpay.plugin.KernelService.CompleteTransfer:input_type -> okpay.plugin.CompleteTransferRequest
	29, // 40: okpay.plugin.KernelService.RecordCNotify:input_type -> okpay.plugin.RecordCNotifyRequest
	30, // 41: okpay.plugin.KernelService.LockOrderExt:input_type -> okpay.plugin.LockOrderExtRequest
	10, // 42: okpay.plugin.PluginService.Info:output_type -> okpay.plugin.PluginInfoResponse
	13, // 43: okpay.plugin.PluginService.Create:output_type -> okpay.plugin.CreateResponse
	15, // 44: okpay.plugin.PluginService.Query:output_type -> okpay.plugin.QueryResponse
	17, // 45: okpay.plugin.PluginService.Refund:output_type -> okpay.plugin.RefundResponse
	19, // 46: okpay.plugin.PluginService.Transfer:output_type -> okpay.plugin.TransferResponse
	21, // 47: okpay.plugin.PluginService.Balance:output_type -> okpay.plugin.BalanceResponse
	23, // 48: okpay.plugin.PluginService.InvokeFunc:output_type -> okpay.plugin.InvokeFuncResponse
	25, // 49: okpay.plugin.KernelService.CompleteOrder:output_type -> okpay.plugin.Ack
	25, // 50: okpay.plugin.KernelService.CompleteRefund:output_type -> okpay.plugin.Ack
	25, // 51: okpay.plugin.KernelService.CompleteTransfer:output_type -> okpay.plugin.Ack
	25, // 52: okpay.plugin.KernelService.RecordCNotify:output_type -> okpay.plugin.Ack
	31, // 53: okpay.plugin.KernelService.LockOrderExt:output_type -> okpay.plugin.LockOrderExtResponse
	42, // [42:54] is the sub-list for method output_type
	30, // [30:42] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
