// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BizType int32

const (
	BizType_BIZ_TYPE_INVALID  BizType = 0
	BizType_BIZ_TYPE_ORDER    BizType = 1
	BizType_BIZ_TYPE_REFUND   BizType = 2
	BizType_BIZ_TYPE_TRANSFER BizType = 3
	BizType_BIZ_TYPE_BALANCE  BizType = 4
)

// Enum value maps for BizType.
var (
	BizType_name = map[int32]string{
		0: "BIZ_TYPE_INVALID",
		1: "BIZ_TYPE_ORDER",
		2: "BIZ_TYPE_REFUND",
		3: "BIZ_TYPE_TRANSFER",
		4: "BIZ_TYPE_BALANCE",
	}
	BizType_value = map[string]int32{
		"BIZ_TYPE_INVALID":  0,
		"BIZ_TYPE_ORDER":    1,
		"BIZ_TYPE_REFUND":   2,
		"BIZ_TYPE_TRANSFER": 3,
		"BIZ_TYPE_BALANCE":  4,
	}
)

func (x BizType) Enum() *BizType {
	p := new(BizType)
	*p = x
	return p
}

func (x BizType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BizType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (BizType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x BizType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BizType.Descriptor instead.
func (BizType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type BizState int32

const (
	BizState_BIZ_STATE_INVALID    BizState = 0
	BizState_BIZ_STATE_FAILED     BizState = 1
	BizState_BIZ_STATE_PROCESSING BizState = 2
	BizState_BIZ_STATE_SUCCEEDED  BizState = 3
)

// Enum value maps for BizState.
var (
	BizState_name = map[int32]string{
		0: "BIZ_STATE_INVALID",
		1: "BIZ_STATE_FAILED",
		2: "BIZ_STATE_PROCESSING",
		3: "BIZ_STATE_SUCCEEDED",
	}
	BizState_value = map[string]int32{
		"BIZ_STATE_INVALID":    0,
		"BIZ_STATE_FAILED":     1,
		"BIZ_STATE_PROCESSING": 2,
		"BIZ_STATE_SUCCEEDED":  3,
	}
)

func (x BizState) Enum() *BizState {
	p := new(BizState)
	*p = x
	return p
}

func (x BizState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BizState) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (BizState) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x BizState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BizState.Descriptor instead.
func (BizState) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

type HeaderKV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderKV) Reset() {
	*x = HeaderKV{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderKV) ProtoMessage() {}

func (x *HeaderKV) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderKV.ProtoReflect.Descriptor instead.
func (*HeaderKV) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderKV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeaderKV) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OrderSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeNo       string                 `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	OutTradeNo    string                 `protobuf:"bytes,2,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	ApiTradeNo    string                 `protobuf:"bytes,3,opt,name=api_trade_no,json=apiTradeNo,proto3" json:"api_trade_no,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Plugin        string                 `protobuf:"bytes,6,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Channel       int64                  `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"`
	Cid           int64                  `protobuf:"varint,8,opt,name=cid,proto3" json:"cid,omitempty"`
	Code          int64                  `protobuf:"varint,9,opt,name=code,proto3" json:"code,omitempty"`
	Subject       string                 `protobuf:"bytes,10,opt,name=subject,proto3" json:"subject,omitempty"`
	Amount        int64                  `protobuf:"varint,11,opt,name=amount,proto3" json:"amount,omitempty"`
	Real          int64                  `protobuf:"varint,12,opt,name=real,proto3" json:"real,omitempty"`
	Fee           int64                  `protobuf:"varint,13,opt,name=fee,proto3" json:"fee,omitempty"`
	Get           int64                  `protobuf:"varint,14,opt,name=get,proto3" json:"get,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,15,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,16,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	Param         string                 `protobuf:"bytes,17,opt,name=param,proto3" json:"param,omitempty"`
	Domain        string                 `protobuf:"bytes,18,opt,name=domain,proto3" json:"domain,omitempty"`
	IpBuyer       string                 `protobuf:"bytes,19,opt,name=ip_buyer,json=ipBuyer,proto3" json:"ip_buyer,omitempty"`
	IpSource      string                 `protobuf:"bytes,20,opt,name=ip_source,json=ipSource,proto3" json:"ip_source,omitempty"`
	Buyer         string                 `protobuf:"bytes,21,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Status        int32                  `protobuf:"varint,22,opt,name=status,proto3" json:"status,omitempty"`
	Notify        int32                  `protobuf:"varint,23,opt,name=notify,proto3" json:"notify,omitempty"`
	ReqMs         int32                  `protobuf:"varint,24,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ReqCount      int32                  `protobuf:"varint,25,opt,name=req_count,json=reqCount,proto3" json:"req_count,omitempty"`
	ReqBody       string                 `protobuf:"bytes,26,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,27,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	Ext           string                 `protobuf:"bytes,28,opt,name=ext,proto3" json:"ext,omitempty"`
	Result        string                 `protobuf:"bytes,29,opt,name=result,proto3" json:"result,omitempty"`
	Endtime       *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=endtime,proto3" json:"endtime,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,32,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSnapshot) Reset() {
	*x = OrderSnapshot{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSnapshot) ProtoMessage() {}

func (x *OrderSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSnapshot.ProtoReflect.Descriptor instead.
func (*OrderSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *OrderSnapshot) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *OrderSnapshot) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *OrderSnapshot) GetApiTradeNo() string {
	if x != nil {
		return x.ApiTradeNo
	}
	return ""
}

func (x *OrderSnapshot) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *OrderSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderSnapshot) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *OrderSnapshot) GetChannel() int64 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *OrderSnapshot) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *OrderSnapshot) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderSnapshot) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OrderSnapshot) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderSnapshot) GetReal() int64 {
	if x != nil {
		return x.Real
	}
	return 0
}

func (x *OrderSnapshot) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *OrderSnapshot) GetGet() int64 {
	if x != nil {
		return x.Get
	}
	return 0
}

func (x *OrderSnapshot) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *OrderSnapshot) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *OrderSnapshot) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *OrderSnapshot) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *OrderSnapshot) GetIpBuyer() string {
	if x != nil {
		return x.IpBuyer
	}
	return ""
}

func (x *OrderSnapshot) GetIpSource() string {
	if x != nil {
		return x.IpSource
	}
	return ""
}

func (x *OrderSnapshot) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *OrderSnapshot) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderSnapshot) GetNotify() int32 {
	if x != nil {
		return x.Notify
	}
	return 0
}

func (x *OrderSnapshot) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *OrderSnapshot) GetReqCount() int32 {
	if x != nil {
		return x.ReqCount
	}
	return 0
}

func (x *OrderSnapshot) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *OrderSnapshot) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *OrderSnapshot) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *OrderSnapshot) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *OrderSnapshot) GetEndtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Endtime
	}
	return nil
}

func (x *OrderSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RefundSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundNo      string                 `protobuf:"bytes,1,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	TradeNo       string                 `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	OutRefundNo   string                 `protobuf:"bytes,3,opt,name=out_refund_no,json=outRefundNo,proto3" json:"out_refund_no,omitempty"`
	ApiRefundNo   string                 `protobuf:"bytes,4,opt,name=api_refund_no,json=apiRefundNo,proto3" json:"api_refund_no,omitempty"`
	Uid           int64                  `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Channel       int64                  `protobuf:"varint,6,opt,name=channel,proto3" json:"channel,omitempty"`
	Cid           int64                  `protobuf:"varint,7,opt,name=cid,proto3" json:"cid,omitempty"`
	Amount        int64                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,9,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReqMs         int32                  `protobuf:"varint,10,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ReqBody       string                 `protobuf:"bytes,11,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,12,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	Notify        int32                  `protobuf:"varint,13,opt,name=notify,proto3" json:"notify,omitempty"`
	Status        int32                  `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,15,opt,name=remark,proto3" json:"remark,omitempty"`
	Result        string                 `protobuf:"bytes,16,opt,name=result,proto3" json:"result,omitempty"`
	Endtime       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=endtime,proto3" json:"endtime,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundSnapshot) Reset() {
	*x = RefundSnapshot{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundSnapshot) ProtoMessage() {}

func (x *RefundSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundSnapshot.ProtoReflect.Descriptor instead.
func (*RefundSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *RefundSnapshot) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *RefundSnapshot) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RefundSnapshot) GetOutRefundNo() string {
	if x != nil {
		return x.OutRefundNo
	}
	return ""
}

func (x *RefundSnapshot) GetApiRefundNo() string {
	if x != nil {
		return x.ApiRefundNo
	}
	return ""
}

func (x *RefundSnapshot) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RefundSnapshot) GetChannel() int64 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *RefundSnapshot) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *RefundSnapshot) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundSnapshot) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *RefundSnapshot) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *RefundSnapshot) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *RefundSnapshot) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *RefundSnapshot) GetNotify() int32 {
	if x != nil {
		return x.Notify
	}
	return 0
}

func (x *RefundSnapshot) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RefundSnapshot) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RefundSnapshot) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RefundSnapshot) GetEndtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Endtime
	}
	return nil
}

func (x *RefundSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RefundSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TransferSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeNo       string                 `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	ApiTradeNo    string                 `protobuf:"bytes,2,opt,name=api_trade_no,json=apiTradeNo,proto3" json:"api_trade_no,omitempty"`
	OutTradeNo    string                 `protobuf:"bytes,3,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Business      int32                  `protobuf:"varint,5,opt,name=business,proto3" json:"business,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Channel       int64                  `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"`
	Cid           int64                  `protobuf:"varint,8,opt,name=cid,proto3" json:"cid,omitempty"`
	Code          int64                  `protobuf:"varint,9,opt,name=code,proto3" json:"code,omitempty"`
	Amount        int64                  `protobuf:"varint,10,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           int64                  `protobuf:"varint,11,opt,name=fee,proto3" json:"fee,omitempty"`
	Cost          int64                  `protobuf:"varint,12,opt,name=cost,proto3" json:"cost,omitempty"`
	BankName      string                 `protobuf:"bytes,13,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	CardName      string                 `protobuf:"bytes,14,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	CardNo        string                 `protobuf:"bytes,15,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	BranchName    string                 `protobuf:"bytes,16,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,17,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReqMs         int32                  `protobuf:"varint,18,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ReqBody       string                 `protobuf:"bytes,19,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,20,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	Notify        int32                  `protobuf:"varint,21,opt,name=notify,proto3" json:"notify,omitempty"`
	Status        int32                  `protobuf:"varint,22,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,23,opt,name=remark,proto3" json:"remark,omitempty"`
	Result        string                 `protobuf:"bytes,24,opt,name=result,proto3" json:"result,omitempty"`
	Endtime       *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=endtime,proto3" json:"endtime,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferSnapshot) Reset() {
	*x = TransferSnapshot{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferSnapshot) ProtoMessage() {}

func (x *TransferSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferSnapshot.ProtoReflect.Descriptor instead.
func (*TransferSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *TransferSnapshot) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *TransferSnapshot) GetApiTradeNo() string {
	if x != nil {
		return x.ApiTradeNo
	}
	return ""
}

func (x *TransferSnapshot) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *TransferSnapshot) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TransferSnapshot) GetBusiness() int32 {
	if x != nil {
		return x.Business
	}
	return 0
}

func (x *TransferSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransferSnapshot) GetChannel() int64 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TransferSnapshot) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *TransferSnapshot) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TransferSnapshot) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferSnapshot) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransferSnapshot) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *TransferSnapshot) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *TransferSnapshot) GetCardName() string {
	if x != nil {
		return x.CardName
	}
	return ""
}

func (x *TransferSnapshot) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *TransferSnapshot) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *TransferSnapshot) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *TransferSnapshot) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *TransferSnapshot) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *TransferSnapshot) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *TransferSnapshot) GetNotify() int32 {
	if x != nil {
		return x.Notify
	}
	return 0
}

func (x *TransferSnapshot) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TransferSnapshot) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TransferSnapshot) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TransferSnapshot) GetEndtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Endtime
	}
	return nil
}

func (x *TransferSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransferSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ChannelSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Plugin        string                 `protobuf:"bytes,3,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Rate          string                 `protobuf:"bytes,5,opt,name=rate,proto3" json:"rate,omitempty"`
	FixedFee      int64                  `protobuf:"varint,6,opt,name=fixed_fee,json=fixedFee,proto3" json:"fixed_fee,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Action        int32                  `protobuf:"varint,8,opt,name=action,proto3" json:"action,omitempty"`
	Domain        string                 `protobuf:"bytes,9,opt,name=domain,proto3" json:"domain,omitempty"`
	ConfigJsonRaw []byte                 `protobuf:"bytes,10,opt,name=config_json_raw,json=configJsonRaw,proto3" json:"config_json_raw,omitempty"`
	Daylimit      int64                  `protobuf:"varint,11,opt,name=daylimit,proto3" json:"daylimit,omitempty"`
	Daynumber     int64                  `protobuf:"varint,12,opt,name=daynumber,proto3" json:"daynumber,omitempty"`
	Paymin        int64                  `protobuf:"varint,13,opt,name=paymin,proto3" json:"paymin,omitempty"`
	Paymax        int64                  `protobuf:"varint,14,opt,name=paymax,proto3" json:"paymax,omitempty"`
	Author        int64                  `protobuf:"varint,15,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelSnapshot) Reset() {
	*x = ChannelSnapshot{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSnapshot) ProtoMessage() {}

func (x *ChannelSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSnapshot.ProtoReflect.Descriptor instead.
func (*ChannelSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelSnapshot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChannelSnapshot) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ChannelSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelSnapshot) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *ChannelSnapshot) GetFixedFee() int64 {
	if x != nil {
		return x.FixedFee
	}
	return 0
}

func (x *ChannelSnapshot) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChannelSnapshot) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *ChannelSnapshot) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ChannelSnapshot) GetConfigJsonRaw() []byte {
	if x != nil {
		return x.ConfigJsonRaw
	}
	return nil
}

func (x *ChannelSnapshot) GetDaylimit() int64 {
	if x != nil {
		return x.Daylimit
	}
	return 0
}

func (x *ChannelSnapshot) GetDaynumber() int64 {
	if x != nil {
		return x.Daynumber
	}
	return 0
}

func (x *ChannelSnapshot) GetPaymin() int64 {
	if x != nil {
		return x.Paymin
	}
	return 0
}

func (x *ChannelSnapshot) GetPaymax() int64 {
	if x != nil {
		return x.Paymax
	}
	return 0
}

func (x *ChannelSnapshot) GetAuthor() int64 {
	if x != nil {
		return x.Author
	}
	return 0
}

func (x *ChannelSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChannelSnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ConfigSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteDomain    string                 `protobuf:"bytes,1,opt,name=site_domain,json=siteDomain,proto3" json:"site_domain,omitempty"`
	NotifyDomain  string                 `protobuf:"bytes,2,opt,name=notify_domain,json=notifyDomain,proto3" json:"notify_domain,omitempty"`
	Localhost     string                 `protobuf:"bytes,3,opt,name=localhost,proto3" json:"localhost,omitempty"`
	GoodsName     string                 `protobuf:"bytes,4,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	CreateTimeout string                 `protobuf:"bytes,5,opt,name=create_timeout,json=createTimeout,proto3" json:"create_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigSnapshot) GetSiteDomain() string {
	if x != nil {
		return x.SiteDomain
	}
	return ""
}

func (x *ConfigSnapshot) GetNotifyDomain() string {
	if x != nil {
		return x.NotifyDomain
	}
	return ""
}

func (x *ConfigSnapshot) GetLocalhost() string {
	if x != nil {
		return x.Localhost
	}
	return ""
}

func (x *ConfigSnapshot) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *ConfigSnapshot) GetCreateTimeout() string {
	if x != nil {
		return x.CreateTimeout
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Ua            string                 `protobuf:"bytes,4,opt,name=ua,proto3" json:"ua,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Headers       []*HeaderKV            `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Request) GetUa() string {
	if x != nil {
		return x.Ua
	}
	return ""
}

func (x *Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetHeaders() []*HeaderKV {
	if x != nil {
		return x.Headers
	}
	return nil
}

type InvokeContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FuncName       string                 `protobuf:"bytes,2,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	Order          *OrderSnapshot         `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Refund         *RefundSnapshot        `protobuf:"bytes,4,opt,name=refund,proto3" json:"refund,omitempty"`
	Transfer       *TransferSnapshot      `protobuf:"bytes,5,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Channel        *ChannelSnapshot       `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
	Config         *ConfigSnapshot        `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	Request        *Request               `protobuf:"bytes,8,opt,name=request,proto3" json:"request,omitempty"`
	KernelBrokerId uint32                 `protobuf:"varint,9,opt,name=kernel_broker_id,json=kernelBrokerId,proto3" json:"kernel_broker_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvokeContext) Reset() {
	*x = InvokeContext{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeContext) ProtoMessage() {}

func (x *InvokeContext) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeContext.ProtoReflect.Descriptor instead.
func (*InvokeContext) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeContext) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *InvokeContext) GetOrder() *OrderSnapshot {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *InvokeContext) GetRefund() *RefundSnapshot {
	if x != nil {
		return x.Refund
	}
	return nil
}

func (x *InvokeContext) GetTransfer() *TransferSnapshot {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *InvokeContext) GetChannel() *ChannelSnapshot {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *InvokeContext) GetConfig() *ConfigSnapshot {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InvokeContext) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *InvokeContext) GetKernelBrokerId() uint32 {
	if x != nil {
		return x.KernelBrokerId
	}
	return 0
}

type PluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfoRequest) Reset() {
	*x = PluginInfoRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoRequest) ProtoMessage() {}

func (x *PluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoRequest.ProtoReflect.Descriptor instead.
func (*PluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

type InputField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputField) Reset() {
	*x = InputField{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputField) ProtoMessage() {}

func (x *InputField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputField.ProtoReflect.Descriptor instead.
func (*InputField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *InputField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InputField) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *InputField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *InputField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *InputField) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type PluginInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Paytypes      []string               `protobuf:"bytes,4,rep,name=paytypes,proto3" json:"paytypes,omitempty"`
	Transtypes    []string               `protobuf:"bytes,5,rep,name=transtypes,proto3" json:"transtypes,omitempty"`
	Inputs        map[string]*InputField `protobuf:"bytes,6,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Note          string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfoResponse) Reset() {
	*x = PluginInfoResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfoResponse) ProtoMessage() {}

func (x *PluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfoResponse.ProtoReflect.Descriptor instead.
func (*PluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *PluginInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfoResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PluginInfoResponse) GetPaytypes() []string {
	if x != nil {
		return x.Paytypes
	}
	return nil
}

func (x *PluginInfoResponse) GetTranstypes() []string {
	if x != nil {
		return x.Transtypes
	}
	return nil
}

func (x *PluginInfoResponse) GetInputs() map[string]*InputField {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *PluginInfoResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Page          string                 `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	DataJsonRaw   []byte                 `protobuf:"bytes,5,opt,name=data_json_raw,json=dataJsonRaw,proto3" json:"data_json_raw,omitempty"`
	DataText      string                 `protobuf:"bytes,6,opt,name=data_text,json=dataText,proto3" json:"data_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PageResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PageResponse) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *PageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PageResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PageResponse) GetDataJsonRaw() []byte {
	if x != nil {
		return x.DataJsonRaw
	}
	return nil
}

func (x *PageResponse) GetDataText() string {
	if x != nil {
		return x.DataText
	}
	return ""
}

type HandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *InvokeContext         `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequest) Reset() {
	*x = HandleRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequest) ProtoMessage() {}

func (x *HandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequest.ProtoReflect.Descriptor instead.
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *HandleRequest) GetCtx() *InvokeContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type HandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResponse          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleResponse) Reset() {
	*x = HandleResponse{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResponse) ProtoMessage() {}

func (x *HandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResponse.ProtoReflect.Descriptor instead.
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *HandleResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type BizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *InvokeContext         `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	BizType       BizType                `protobuf:"varint,2,opt,name=biz_type,json=bizType,proto3,enum=okpay.plugin.BizType" json:"biz_type,omitempty"`
	BizNo         string                 `protobuf:"bytes,3,opt,name=biz_no,json=bizNo,proto3" json:"biz_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BizRequest) Reset() {
	*x = BizRequest{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BizRequest) ProtoMessage() {}

func (x *BizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BizRequest.ProtoReflect.Descriptor instead.
func (*BizRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *BizRequest) GetCtx() *InvokeContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *BizRequest) GetBizType() BizType {
	if x != nil {
		return x.BizType
	}
	return BizType_BIZ_TYPE_INVALID
}

func (x *BizRequest) GetBizNo() string {
	if x != nil {
		return x.BizNo
	}
	return ""
}

type RequestTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqMs         int32                  `protobuf:"varint,1,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ReqBody       string                 `protobuf:"bytes,2,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,3,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTrace) Reset() {
	*x = RequestTrace{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTrace) ProtoMessage() {}

func (x *RequestTrace) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTrace.ProtoReflect.Descriptor instead.
func (*RequestTrace) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *RequestTrace) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *RequestTrace) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *RequestTrace) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

type BizResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         BizState               `protobuf:"varint,1,opt,name=state,proto3,enum=okpay.plugin.BizState" json:"state,omitempty"`
	ApiNo         string                 `protobuf:"bytes,2,opt,name=api_no,json=apiNo,proto3" json:"api_no,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Trace         *RequestTrace          `protobuf:"bytes,5,opt,name=trace,proto3" json:"trace,omitempty"`
	Balance       string                 `protobuf:"bytes,6,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BizResult) Reset() {
	*x = BizResult{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BizResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BizResult) ProtoMessage() {}

func (x *BizResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BizResult.ProtoReflect.Descriptor instead.
func (*BizResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *BizResult) GetState() BizState {
	if x != nil {
		return x.State
	}
	return BizState_BIZ_STATE_INVALID
}

func (x *BizResult) GetApiNo() string {
	if x != nil {
		return x.ApiNo
	}
	return ""
}

func (x *BizResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BizResult) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BizResult) GetTrace() *RequestTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *BizResult) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type PluginError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginError) Reset() {
	*x = PluginError{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginError) ProtoMessage() {}

func (x *PluginError) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginError.ProtoReflect.Descriptor instead.
func (*PluginError) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *PluginError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PluginError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error         *PluginError           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *Ack) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Ack) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Ack) GetError() *PluginError {
	if x != nil {
		return x.Error
	}
	return nil
}

type CompleteBizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	BizType       BizType                `protobuf:"varint,2,opt,name=biz_type,json=bizType,proto3,enum=okpay.plugin.BizType" json:"biz_type,omitempty"`
	BizNo         string                 `protobuf:"bytes,3,opt,name=biz_no,json=bizNo,proto3" json:"biz_no,omitempty"`
	State         BizState               `protobuf:"varint,4,opt,name=state,proto3,enum=okpay.plugin.BizState" json:"state,omitempty"`
	ApiNo         string                 `protobuf:"bytes,5,opt,name=api_no,json=apiNo,proto3" json:"api_no,omitempty"`
	Code          string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	RespBody      string                 `protobuf:"bytes,8,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	Buyer         string                 `protobuf:"bytes,9,opt,name=buyer,proto3" json:"buyer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBizRequest) Reset() {
	*x = CompleteBizRequest{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBizRequest) ProtoMessage() {}

func (x *CompleteBizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBizRequest.ProtoReflect.Descriptor instead.
func (*CompleteBizRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *CompleteBizRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompleteBizRequest) GetBizType() BizType {
	if x != nil {
		return x.BizType
	}
	return BizType_BIZ_TYPE_INVALID
}

func (x *CompleteBizRequest) GetBizNo() string {
	if x != nil {
		return x.BizNo
	}
	return ""
}

func (x *CompleteBizRequest) GetState() BizState {
	if x != nil {
		return x.State
	}
	return BizState_BIZ_STATE_INVALID
}

func (x *CompleteBizRequest) GetApiNo() string {
	if x != nil {
		return x.ApiNo
	}
	return ""
}

func (x *CompleteBizRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteBizRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CompleteBizRequest) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *CompleteBizRequest) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

type LockOrderExtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TradeNo       string                 `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	ReqBody       string                 `protobuf:"bytes,3,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RespBody      string                 `protobuf:"bytes,4,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`
	ReqCount      int32                  `protobuf:"varint,5,opt,name=req_count,json=reqCount,proto3" json:"req_count,omitempty"`
	ReqMs         int32                  `protobuf:"varint,6,opt,name=req_ms,json=reqMs,proto3" json:"req_ms,omitempty"`
	ExtJsonRaw    []byte                 `protobuf:"bytes,7,opt,name=ext_json_raw,json=extJsonRaw,proto3" json:"ext_json_raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockOrderExtRequest) Reset() {
	*x = LockOrderExtRequest{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockOrderExtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockOrderExtRequest) ProtoMessage() {}

func (x *LockOrderExtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockOrderExtRequest.ProtoReflect.Descriptor instead.
func (*LockOrderExtRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *LockOrderExtRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LockOrderExtRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *LockOrderExtRequest) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *LockOrderExtRequest) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *LockOrderExtRequest) GetReqCount() int32 {
	if x != nil {
		return x.ReqCount
	}
	return 0
}

func (x *LockOrderExtRequest) GetReqMs() int32 {
	if x != nil {
		return x.ReqMs
	}
	return 0
}

func (x *LockOrderExtRequest) GetExtJsonRaw() []byte {
	if x != nil {
		return x.ExtJsonRaw
	}
	return nil
}

type LockOrderExtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtJsonRaw    []byte                 `protobuf:"bytes,1,opt,name=ext_json_raw,json=extJsonRaw,proto3" json:"ext_json_raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockOrderExtResponse) Reset() {
	*x = LockOrderExtResponse{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockOrderExtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockOrderExtResponse) ProtoMessage() {}

func (x *LockOrderExtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockOrderExtResponse.ProtoReflect.Descriptor instead.
func (*LockOrderExtResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *LockOrderExtResponse) GetExtJsonRaw() []byte {
	if x != nil {
		return x.ExtJsonRaw
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\fokpay.plugin\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\bHeaderKV\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x82\a\n" +
	"\rOrderSnapshot\x12\x19\n" +
	"\btrade_no\x18\x01 \x01(\tR\atradeNo\x12 \n" +
	"\fout_trade_no\x18\x02 \x01(\tR\n" +
	"outTradeNo\x12 \n" +
	"\fapi_trade_no\x18\x03 \x01(\tR\n" +
	"apiTradeNo\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06plugin\x18\x06 \x01(\tR\x06plugin\x12\x18\n" +
	"\achannel\x18\a \x01(\x03R\achannel\x12\x10\n" +
	"\x03cid\x18\b \x01(\x03R\x03cid\x12\x12\n" +
	"\x04code\x18\t \x01(\x03R\x04code\x12\x18\n" +
	"\asubject\x18\n" +
	" \x01(\tR\asubject\x12\x16\n" +
	"\x06amount\x18\v \x01(\x03R\x06amount\x12\x12\n" +
	"\x04real\x18\f \x01(\x03R\x04real\x12\x10\n" +
	"\x03fee\x18\r \x01(\x03R\x03fee\x12\x10\n" +
	"\x03get\x18\x0e \x01(\x03R\x03get\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x0f \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\x10 \x01(\tR\treturnUrl\x12\x14\n" +
	"\x05param\x18\x11 \x01(\tR\x05param\x12\x16\n" +
	"\x06domain\x18\x12 \x01(\tR\x06domain\x12\x19\n" +
	"\bip_buyer\x18\x13 \x01(\tR\aipBuyer\x12\x1b\n" +
	"\tip_source\x18\x14 \x01(\tR\bipSource\x12\x14\n" +
	"\x05buyer\x18\x15 \x01(\tR\x05buyer\x12\x16\n" +
	"\x06status\x18\x16 \x01(\x05R\x06status\x12\x16\n" +
	"\x06notify\x18\x17 \x01(\x05R\x06notify\x12\x15\n" +
	"\x06req_ms\x18\x18 \x01(\x05R\x05reqMs\x12\x1b\n" +
	"\treq_count\x18\x19 \x01(\x05R\breqCount\x12\x19\n" +
	"\breq_body\x18\x1a \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\x1b \x01(\tR\brespBody\x12\x10\n" +
	"\x03ext\x18\x1c \x01(\tR\x03ext\x12\x16\n" +
	"\x06result\x18\x1d \x01(\tR\x06result\x124\n" +
	"\aendtime\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\aendtime\x129\n" +
	"\n" +
	"created_at\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18  \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe0\x04\n" +
	"\x0eRefundSnapshot\x12\x1b\n" +
	"\trefund_no\x18\x01 \x01(\tR\brefundNo\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\x12\"\n" +
	"\rout_refund_no\x18\x03 \x01(\tR\voutRefundNo\x12\"\n" +
	"\rapi_refund_no\x18\x04 \x01(\tR\vapiRefundNo\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\x03R\x03uid\x12\x18\n" +
	"\achannel\x18\x06 \x01(\x03R\achannel\x12\x10\n" +
	"\x03cid\x18\a \x01(\x03R\x03cid\x12\x16\n" +
	"\x06amount\x18\b \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"notify_url\x18\t \x01(\tR\tnotifyUrl\x12\x15\n" +
	"\x06req_ms\x18\n" +
	" \x01(\x05R\x05reqMs\x12\x19\n" +
	"\breq_body\x18\v \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\f \x01(\tR\brespBody\x12\x16\n" +
	"\x06notify\x18\r \x01(\x05R\x06notify\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x0f \x01(\tR\x06remark\x12\x16\n" +
	"\x06result\x18\x10 \x01(\tR\x06result\x124\n" +
	"\aendtime\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\aendtime\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x06\n" +
	"\x10TransferSnapshot\x12\x19\n" +
	"\btrade_no\x18\x01 \x01(\tR\atradeNo\x12 \n" +
	"\fapi_trade_no\x18\x02 \x01(\tR\n" +
	"apiTradeNo\x12 \n" +
	"\fout_trade_no\x18\x03 \x01(\tR\n" +
	"outTradeNo\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bbusiness\x18\x05 \x01(\x05R\bbusiness\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x18\n" +
	"\achannel\x18\a \x01(\x03R\achannel\x12\x10\n" +
	"\x03cid\x18\b \x01(\x03R\x03cid\x12\x12\n" +
	"\x04code\x18\t \x01(\x03R\x04code\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x03R\x06amount\x12\x10\n" +
	"\x03fee\x18\v \x01(\x03R\x03fee\x12\x12\n" +
	"\x04cost\x18\f \x01(\x03R\x04cost\x12\x1b\n" +
	"\tbank_name\x18\r \x01(\tR\bbankName\x12\x1b\n" +
	"\tcard_name\x18\x0e \x01(\tR\bcardName\x12\x17\n" +
	"\acard_no\x18\x0f \x01(\tR\x06cardNo\x12\x1f\n" +
	"\vbranch_name\x18\x10 \x01(\tR\n" +
	"branchName\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x11 \x01(\tR\tnotifyUrl\x12\x15\n" +
	"\x06req_ms\x18\x12 \x01(\x05R\x05reqMs\x12\x19\n" +
	"\breq_body\x18\x13 \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\x14 \x01(\tR\brespBody\x12\x16\n" +
	"\x06notify\x18\x15 \x01(\x05R\x06notify\x12\x16\n" +
	"\x06status\x18\x16 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x17 \x01(\tR\x06remark\x12\x16\n" +
	"\x06result\x18\x18 \x01(\tR\x06result\x124\n" +
	"\aendtime\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\aendtime\x129\n" +
	"\n" +
	"created_at\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfa\x03\n" +
	"\x0fChannelSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06plugin\x18\x03 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\tR\x04rate\x12\x1b\n" +
	"\tfixed_fee\x18\x06 \x01(\x03R\bfixedFee\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x16\n" +
	"\x06action\x18\b \x01(\x05R\x06action\x12\x16\n" +
	"\x06domain\x18\t \x01(\tR\x06domain\x12&\n" +
	"\x0fconfig_json_raw\x18\n" +
	" \x01(\fR\rconfigJsonRaw\x12\x1a\n" +
	"\bdaylimit\x18\v \x01(\x03R\bdaylimit\x12\x1c\n" +
	"\tdaynumber\x18\f \x01(\x03R\tdaynumber\x12\x16\n" +
	"\x06paymin\x18\r \x01(\x03R\x06paymin\x12\x16\n" +
	"\x06paymax\x18\x0e \x01(\x03R\x06paymax\x12\x16\n" +
	"\x06author\x18\x0f \x01(\x03R\x06author\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc0\x01\n" +
	"\x0eConfigSnapshot\x12\x1f\n" +
	"\vsite_domain\x18\x01 \x01(\tR\n" +
	"siteDomain\x12#\n" +
	"\rnotify_domain\x18\x02 \x01(\tR\fnotifyDomain\x12\x1c\n" +
	"\tlocalhost\x18\x03 \x01(\tR\tlocalhost\x12\x1d\n" +
	"\n" +
	"goods_name\x18\x04 \x01(\tR\tgoodsName\x12%\n" +
	"\x0ecreate_timeout\x18\x05 \x01(\tR\rcreateTimeoutJ\x04\b\x06\x10\a\"\xb5\x01\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02ua\x18\x04 \x01(\tR\x02ua\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x120\n" +
	"\aheaders\x18\a \x03(\v2\x16.okpay.plugin.HeaderKVR\aheadersJ\x04\b\b\x10\v\"\xba\x03\n" +
	"\rInvokeContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tfunc_name\x18\x02 \x01(\tR\bfuncName\x121\n" +
	"\x05order\x18\x03 \x01(\v2\x1b.okpay.plugin.OrderSnapshotR\x05order\x124\n" +
	"\x06refund\x18\x04 \x01(\v2\x1c.okpay.plugin.RefundSnapshotR\x06refund\x12:\n" +
	"\btransfer\x18\x05 \x01(\v2\x1e.okpay.plugin.TransferSnapshotR\btransfer\x127\n" +
	"\achannel\x18\x06 \x01(\v2\x1d.okpay.plugin.ChannelSnapshotR\achannel\x124\n" +
	"\x06config\x18\a \x01(\v2\x1c.okpay.plugin.ConfigSnapshotR\x06config\x12/\n" +
	"\arequest\x18\b \x01(\v2\x15.okpay.plugin.RequestR\arequest\x12(\n" +
	"\x10kernel_broker_id\x18\t \x01(\rR\x0ekernelBrokerId\"\x13\n" +
	"\x11PluginInfoRequest\"\x86\x02\n" +
	"\n" +
	"InputField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\x12?\n" +
	"\aoptions\x18\x06 \x03(\v2%.okpay.plugin.InputField.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x02\n" +
	"\x12PluginInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1a\n" +
	"\bpaytypes\x18\x04 \x03(\tR\bpaytypes\x12\x1e\n" +
	"\n" +
	"transtypes\x18\x05 \x03(\tR\n" +
	"transtypes\x12D\n" +
	"\x06inputs\x18\x06 \x03(\v2,.okpay.plugin.PluginInfoResponse.InputsEntryR\x06inputs\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x1aS\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.okpay.plugin.InputFieldR\x05value:\x028\x01\"\x9b\x01\n" +
	"\fPageResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04page\x18\x02 \x01(\tR\x04page\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\"\n" +
	"\rdata_json_raw\x18\x05 \x01(\fR\vdataJsonRaw\x12\x1b\n" +
	"\tdata_text\x18\x06 \x01(\tR\bdataText\">\n" +
	"\rHandleRequest\x12-\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1b.okpay.plugin.InvokeContextR\x03ctx\"@\n" +
	"\x0eHandleResponse\x12.\n" +
	"\x04page\x18\x01 \x01(\v2\x1a.okpay.plugin.PageResponseR\x04page\"\x84\x01\n" +
	"\n" +
	"BizRequest\x12-\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1b.okpay.plugin.InvokeContextR\x03ctx\x120\n" +
	"\bbiz_type\x18\x02 \x01(\x0e2\x15.okpay.plugin.BizTypeR\abizType\x12\x15\n" +
	"\x06biz_no\x18\x03 \x01(\tR\x05bizNo\"]\n" +
	"\fRequestTrace\x12\x15\n" +
	"\x06req_ms\x18\x01 \x01(\x05R\x05reqMs\x12\x19\n" +
	"\breq_body\x18\x02 \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\x03 \x01(\tR\brespBody\"\xc2\x01\n" +
	"\tBizResult\x12,\n" +
	"\x05state\x18\x01 \x01(\x0e2\x16.okpay.plugin.BizStateR\x05state\x12\x15\n" +
	"\x06api_no\x18\x02 \x01(\tR\x05apiNo\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x120\n" +
	"\x05trace\x18\x05 \x01(\v2\x1a.okpay.plugin.RequestTraceR\x05trace\x12\x18\n" +
	"\abalance\x18\x06 \x01(\tR\abalance\"Y\n" +
	"\vPluginError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"q\n" +
	"\x03Ack\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.okpay.plugin.PluginErrorR\x05error\"\x9a\x02\n" +
	"\x12CompleteBizRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x120\n" +
	"\bbiz_type\x18\x02 \x01(\x0e2\x15.okpay.plugin.BizTypeR\abizType\x12\x15\n" +
	"\x06biz_no\x18\x03 \x01(\tR\x05bizNo\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.okpay.plugin.BizStateR\x05state\x12\x15\n" +
	"\x06api_no\x18\x05 \x01(\tR\x05apiNo\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\a \x01(\tR\x03msg\x12\x1b\n" +
	"\tresp_body\x18\b \x01(\tR\brespBody\x12\x14\n" +
	"\x05buyer\x18\t \x01(\tR\x05buyer\"\xdd\x01\n" +
	"\x13LockOrderExtRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\x12\x19\n" +
	"\breq_body\x18\x03 \x01(\tR\areqBody\x12\x1b\n" +
	"\tresp_body\x18\x04 \x01(\tR\brespBody\x12\x1b\n" +
	"\treq_count\x18\x05 \x01(\x05R\breqCount\x12\x15\n" +
	"\x06req_ms\x18\x06 \x01(\x05R\x05reqMs\x12 \n" +
	"\fext_json_raw\x18\a \x01(\fR\n" +
	"extJsonRaw\"8\n" +
	"\x14LockOrderExtResponse\x12 \n" +
	"\fext_json_raw\x18\x01 \x01(\fR\n" +
	"extJsonRaw*u\n" +
	"\aBizType\x12\x14\n" +
	"\x10BIZ_TYPE_INVALID\x10\x00\x12\x12\n" +
	"\x0eBIZ_TYPE_ORDER\x10\x01\x12\x13\n" +
	"\x0fBIZ_TYPE_REFUND\x10\x02\x12\x15\n" +
	"\x11BIZ_TYPE_TRANSFER\x10\x03\x12\x14\n" +
	"\x10BIZ_TYPE_BALANCE\x10\x04*j\n" +
	"\bBizState\x12\x15\n" +
	"\x11BIZ_STATE_INVALID\x10\x00\x12\x14\n" +
	"\x10BIZ_STATE_FAILED\x10\x01\x12\x18\n" +
	"\x14BIZ_STATE_PROCESSING\x10\x02\x12\x17\n" +
	"\x13BIZ_STATE_SUCCEEDED\x10\x032\x98\x02\n" +
	"\rPluginService\x12I\n" +
	"\x04Info\x12\x1f.okpay.plugin.PluginInfoRequest\x1a .okpay.plugin.PluginInfoResponse\x12C\n" +
	"\x06Handle\x12\x1b.okpay.plugin.HandleRequest\x1a\x1c.okpay.plugin.HandleResponse\x12;\n" +
	"\x06Submit\x12\x18.okpay.plugin.BizRequest\x1a\x17.okpay.plugin.BizResult\x12:\n" +
	"\x05Query\x12\x18.okpay.plugin.BizRequest\x1a\x17.okpay.plugin.BizResult2\xaa\x01\n" +
	"\rKernelService\x12B\n" +
	"\vCompleteBiz\x12 .okpay.plugin.CompleteBizRequest\x1a\x11.okpay.plugin.Ack\x12U\n" +
	"\fLockOrderExt\x12!.okpay.plugin.LockOrderExtRequest\x1a\".okpay.plugin.LockOrderExtResponseB0Z.github.com/ppswws/okpay-plugin-sdk/proto;protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_plugin_proto_goTypes = []any{
	(BizType)(0),                  // 0: okpay.plugin.BizType
	(BizState)(0),                 // 1: okpay.plugin.BizState
	(*HeaderKV)(nil),              // 2: okpay.plugin.HeaderKV
	(*OrderSnapshot)(nil),         // 3: okpay.plugin.OrderSnapshot
	(*RefundSnapshot)(nil),        // 4: okpay.plugin.RefundSnapshot
	(*TransferSnapshot)(nil),      // 5: okpay.plugin.TransferSnapshot
	(*ChannelSnapshot)(nil),       // 6: okpay.plugin.ChannelSnapshot
	(*ConfigSnapshot)(nil),        // 7: okpay.plugin.ConfigSnapshot
	(*Request)(nil),               // 8: okpay.plugin.Request
	(*InvokeContext)(nil),         // 9: okpay.plugin.InvokeContext
	(*PluginInfoRequest)(nil),     // 10: okpay.plugin.PluginInfoRequest
	(*InputField)(nil),            // 11: okpay.plugin.InputField
	(*PluginInfoResponse)(nil),    // 12: okpay.plugin.PluginInfoResponse
	(*PageResponse)(nil),          // 13: okpay.plugin.PageResponse
	(*HandleRequest)(nil),         // 14: okpay.plugin.HandleRequest
	(*HandleResponse)(nil),        // 15: okpay.plugin.HandleResponse
	(*BizRequest)(nil),            // 16: okpay.plugin.BizRequest
	(*RequestTrace)(nil),          // 17: okpay.plugin.RequestTrace
	(*BizResult)(nil),             // 18: okpay.plugin.BizResult
	(*PluginError)(nil),           // 19: okpay.plugin.PluginError
	(*Ack)(nil),                   // 20: okpay.plugin.Ack
	(*CompleteBizRequest)(nil),    // 21: okpay.plugin.CompleteBizRequest
	(*LockOrderExtRequest)(nil),   // 22: okpay.plugin.LockOrderExtRequest
	(*LockOrderExtResponse)(nil),  // 23: okpay.plugin.LockOrderExtResponse
	nil,                           // 24: okpay.plugin.InputField.OptionsEntry
	nil,                           // 25: okpay.plugin.PluginInfoResponse.InputsEntry
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
}
var file_plugin_proto_depIdxs = []int32{
	26, // 0: okpay.plugin.OrderSnapshot.endtime:type_name -> google.protobuf.Timestamp
	26, // 1: okpay.plugin.OrderSnapshot.created_at:type_name -> google.protobuf.Timestamp
	26, // 2: okpay.plugin.OrderSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	26, // 3: okpay.plugin.RefundSnapshot.endtime:type_name -> google.protobuf.Timestamp
	26, // 4: okpay.plugin.RefundSnapshot.created_at:type_name -> google.protobuf.Timestamp
	26, // 5: okpay.plugin.RefundSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	26, // 6: okpay.plugin.TransferSnapshot.endtime:type_name -> google.protobuf.Timestamp
	26, // 7: okpay.plugin.TransferSnapshot.created_at:type_name -> google.protobuf.Timestamp
	26, // 8: okpay.plugin.TransferSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	26, // 9: okpay.plugin.ChannelSnapshot.created_at:type_name -> google.protobuf.Timestamp
	26, // 10: okpay.plugin.ChannelSnapshot.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 11: okpay.plugin.Request.headers:type_name -> okpay.plugin.HeaderKV
	3,  // 12: okpay.plugin.InvokeContext.order:type_name -> okpay.plugin.OrderSnapshot
	4,  // 13: okpay.plugin.InvokeContext.refund:type_name -> okpay.plugin.RefundSnapshot
	5,  // 14: okpay.plugin.InvokeContext.transfer:type_name -> okpay.plugin.TransferSnapshot
	6,  // 15: okpay.plugin.InvokeContext.channel:type_name -> okpay.plugin.ChannelSnapshot
	7,  // 16: okpay.plugin.InvokeContext.config:type_name -> okpay.plugin.ConfigSnapshot
	8,  // 17: okpay.plugin.InvokeContext.request:type_name -> okpay.plugin.Request
	24, // 18: okpay.plugin.InputField.options:type_name -> okpay.plugin.InputField.OptionsEntry
	25, // 19: okpay.plugin.PluginInfoResponse.inputs:type_name -> okpay.plugin.PluginInfoResponse.InputsEntry
	9,  // 20: okpay.plugin.HandleRequest.ctx:type_name -> okpay.plugin.InvokeContext
	13, // 21: okpay.plugin.HandleResponse.page:type_name -> okpay.plugin.PageResponse
	9,  // 22: okpay.plugin.BizRequest.ctx:type_name -> okpay.plugin.InvokeContext
	0,  // 23: okpay.plugin.BizRequest.biz_type:type_name -> okpay.plugin.BizType
	1,  // 24: okpay.plugin.BizResult.state:type_name -> okpay.plugin.BizState
	17, // 25: okpay.plugin.BizResult.trace:type_name -> okpay.plugin.RequestTrace
	19, // 26: okpay.plugin.Ack.error:type_name -> okpay.plugin.PluginError
	0,  // 27: okpay.plugin.CompleteBizRequest.biz_type:type_name -> okpay.plugin.BizType
	1,  // 28: okpay.plugin.CompleteBizRequest.state:type_name -> okpay.plugin.BizState
	11, // 29: okpay.plugin.PluginInfoResponse.InputsEntry.value:type_name -> okpay.plugin.InputField
	10, // 30: okpay.plugin.PluginService.Info:input_type -> okpay.plugin.PluginInfoRequest
	14, // 31: okpay.plugin.PluginService.Handle:input_type -> okpay.plugin.HandleRequest
	16, // 32: okpay.plugin.PluginService.Submit:input_type -> okpay.plugin.BizRequest
	16, // 33: okpay.plugin.PluginService.Query:input_type -> okpay.plugin.BizRequest
	21, // 34: okpay.plugin.KernelService.CompleteBiz:input_type -> okpay.plugin.CompleteBizRequest
	22, // 35: okpay.plugin.KernelService.LockOrderExt:input_type -> okpay.plugin.LockOrderExtRequest
	12, // 36: okpay.plugin.PluginService.Info:output_type -> okpay.plugin.PluginInfoResponse
	15, // 37: okpay.plugin.PluginService.Handle:output_type -> okpay.plugin.HandleResponse
	18, // 38: okpay.plugin.PluginService.Submit:output_type -> okpay.plugin.BizResult
	18, // 39: okpay.plugin.PluginService.Query:output_type -> okpay.plugin.BizResult
	20, // 40: okpay.plugin.KernelService.CompleteBiz:output_type -> okpay.plugin.Ack
	23, // 41: okpay.plugin.KernelService.LockOrderExt:output_type -> okpay.plugin.LockOrderExtResponse
	36, // [36:42] is the sub-list for method output_type
	30, // [30:36] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
